Script started on 2023-01-14 19:31:02-08:00 [TERM="xterm-256color" TTY="/dev/pts/6" COLUMNS="172" LINES="41"]
[?2004h]0;kmfahey@Madeline: ~/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic[01;31m[2023-01-14 19:31:02]
[01;37m[01;32mkmfahey@Madeline[00m:[01;34m~/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic[00m$ python manage.py runserver
[?2004lWatching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/usr/lib/python3/dist-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/lib/python3/dist-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/lib/python3/dist-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 416, in check
    for pattern in self.url_patterns:
  File "/usr/lib/python3/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python3/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/moundmusic/urls.py", line 26, in <module>
    path('buyers', include('buyers.urls')),
  File "/usr/lib/python3/dist-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'buyers'
^C[0m[0m[?2004h]0;kmfahey@Madeline: ~/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic[01;31m[2023-01-14 19:31:07]
[01;37m[01;32mkmfahey@Madeline[00m:[01;34m~/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic[00m$ vim typescript 
[?2004l[?1049h[22;0;0t[>4;2m[?1h=[?2004h[?1004h[1;41r[?12h[?12l[22;2t[22;1t[27m[23m[29m[m[H[2J[?25l[41;1H"typescript" [noeol] 58L, 4096B[2;1Hâ–½[6n[2;1H  [3;1HPzz\[0%m[6n[3;1H           [1;1H[>c]10;?]11;?[1;1HScript started on 2023-01-14 19:31:02-08:00 [TERM="xterm-256color" TTY="/dev/pts/6" COLUMNS="172" LINES="41"]
[38;5;81m^[[m[?2004h[38;5;81m^[[m]0;kmfahey@Madeline: ~/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic[38;5;81m^G^[[m[01;31m[2023-01-14 19:31:02][38;5;81m^M^M[m[2;144H[K[3;1H[38;5;81m^[[m[01;37m[38;5;81m^[[m[01;32mkmfahey@Madeline[38;5;81m^[[m[00m:[38;5;81m^[[m[01;34m~/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic[38;5;81m^[[m[00m$ python manage.py runserver[38;5;81m^M[m[3;162H[K[4;1H[38;5;81m^[[m[?2004l[38;5;81m^M[mWatching for file changes with StatReloader[38;5;81m^M[m
Performing system checks...[38;5;81m^M
^M[m
Exception in thread django-main-thread:[38;5;81m^M[m
Traceback (most recent call last):[38;5;81m^M[m
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner[38;5;81m^M[m
    self.run()[38;5;81m^M[m
  File "/usr/lib/python3.10/threading.py", line 953, in run[38;5;81m^M[m
    self._target(*self._args, **self._kwargs)[38;5;81m^M[m
  File "/usr/lib/python3/dist-packages/django/utils/autoreload.py", line 64, in wrapper[38;5;81m^M[m
    fn(*args, **kwargs)[38;5;81m^M[m
  File "/usr/lib/python3/dist-packages/django/core/management/commands/runserver.py", line 118, in inner_run[38;5;81m^M[m
    self.check(display_num_errors=True)[38;5;81m^M[m
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 419, in check[38;5;81m^M[m
    all_issues = checks.run_checks([38;5;81m^M[m
  File "/usr/lib/python3/dist-packages/django/core/checks/registry.py", line 76, in run_checks[38;5;81m^M[m
    new_errors = check(app_configs=app_configs, databases=databases)[38;5;81m^M[m
  File "/usr/lib/python3/dist-packages/django/core/checks/urls.py", line 13, in check_url_config[38;5;81m^M[m
    return check_resolver(resolver)[38;5;81m^M[m
  File "/usr/lib/python3/dist-packages/django/core/checks/urls.py", line 23, in check_resolver[38;5;81m^M[m
    return check_method()[38;5;81m^M[m
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 416, in check[38;5;81m^M[m
    for pattern in self.url_patterns:[38;5;81m^M[m
  File "/usr/lib/python3/dist-packages/django/utils/functional.py", line 48, in __get__[38;5;81m^M[m
    res = instance.__dict__[self.name] = self.func(instance)[38;5;81m^M[m
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 602, in url_patterns[38;5;81m^M[m
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)[38;5;81m^M[m
  File "/usr/lib/python3/dist-packages/django/utils/functional.py", line 48, in __get__[38;5;81m^M[m
    res = instance.__dict__[self.name] = self.func(instance)[38;5;81m^M[m
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 595, in urlconf_module[38;5;81m^M[m
    return import_module(self.urlconf_name)[38;5;81m^M[m
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module[38;5;81m^M[m
    return _bootstrap._gcd_import(name[level:], package, level)[38;5;81m^M[m
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import[38;5;81m^M[m
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load[38;5;81m^M[m
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked[38;5;81m^M[m
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked[38;5;81m^M[m[41;155H1,1[11CTop[1;1H[?25h[?12$p[?25l[41;155H2[2;1H[?25h[?25l[41;155H3[3;1H[?25h[?25l[41;155H4[4;1H[?25h[?25l[41;155H5[5;1H[?25h[?25l[41;155H6[6;1H[?25h[?25l[41;155H7[7;1H[?25h[?25l[41;1H[K[41;1H/[?25hhome[?25l[1;40r[1;1H[3M[1;41r[38;3HFile "<frozen importlib._bootstrap_external>", line 883, in exec_module[38;5;81m^M[m
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed[38;5;81m^M[m
  File "/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/moundmusic/urls.py", line 26, in <module>[38;5;81m^M[m[41;1H[K[41;155H43,10[9C16%[40;10H[?25h[?25l[1;40r[40;1H
[1;41r[40;5Hpath('buyers', include('buyers.urls')),[38;5;81m^M[m[41;155H[K[41;155H44,10[9C22%[40;10H[?25h[?25l[1;40r[40;1H
[1;41r[40;3HFile "/usr/lib/python3/dist-packages/django/urls/conf.py", line 34, in include[38;5;81m^M[m[41;155H[K[41;155H45,10[9C27%[40;10H[?25h[?25l[1;40r[40;1H
[1;41r[40;5Hurlconf_module = import_module(urlconf_module)[38;5;81m^M[m[41;155H[K[41;155H46,10[9C33%[40;10H[?25h[?25l[1;40r[40;1H
[1;41r[40;3HFile "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module[38;5;81m^M[m[41;155H[K[41;155H47,10[9C38%[40;10H[?25h[?25l[1;40r[40;1H
[1;41r[40;5Hreturn _bootstrap._gcd_import(name[level:], package, level)[38;5;81m^M[m[41;155H[K[41;155H48,10[9C44%[40;10H[?25h[?25l[1;40r[40;1H
[1;41r[40;3HFile "<frozen importlib._bootstrap>", line 1050, in _gcd_import[38;5;81m^M[m[41;155H[K[41;155H49,10[9C50%[40;10H[?25h[?25l[1;40r[40;1H
[1;41r[40;3HFile "<frozen importlib._bootstrap>", line 1027, in _find_and_load[38;5;81m^M[m[41;155H[K[41;155H50,10[9C55%[40;10H[?25h[?25l[1;40r[40;1H
[1;41r[40;3HFile "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked[38;5;81m^M[m[41;155H[K[41;155H51,10[9C61%[40;10H[?25h[?25l[1;40r[40;1H
[1;41r[40;3HFile "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed[38;5;81m^M[m[41;155H[K[41;155H52,10[9C66%[40;10H[?25h[?25l[1;40r[40;1H
[1;41r[40;3HFile "<frozen importlib._bootstrap>", line 1050, in _gcd_import[38;5;81m^M[m[41;155H[K[41;155H53,10[9C72%[40;10H[?25h[?25l[1;40r[40;1H
[1;41r[40;3HFile "<frozen importlib._bootstrap>", line 1027, in _find_and_load[38;5;81m^M[m[41;155H[K[41;155H54,10[9C77%[40;10H[?25h[?25l[41;156H3[39;10H[?25h[?25l[41;156H2[38;10H[?25h[?25l[41;156H1[37;10H[?25h[?25l[41;156H0[36;10H[?25h[?25l[41;155H49[35;10H[?25h[?25l[41;156H8[34;10H[?25h[?25l[41;156H7[33;10H[?25h[?25l[41;156H6[32;10H[?25h[?25l[41;156H5[31;10H[?25h[?25l[41;155H[K[41;1H:[?25hq[?25l[?2004l[>4;m[23;2t[23;1t[41;1H[K[41;1H[?1004l[?2004l[?1l>[?25h[>4;m[?1049l[23;0;0t[?2004h]0;kmfahey@Madeline: ~/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic[01;31m[2023-01-14 19:31:17]
[01;37m[01;32mkmfahey@Madeline[00m:[01;34m~/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic[00m$ vim typescript python manage.py runserver
[?2004lWatching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 14, 2023 - 19:31:37
Django version 3.2.15, using settings 'moundmusic.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[14/Jan/2023 19:31:43] [m"GET /users HTTP/1.1" 200 8718[0m
Not Found: /users/3/buyer_account/2/
[14/Jan/2023 19:31:59] [33m"GET /users/3/buyer_account/2/ HTTP/1.1" 404 6159[0m
[14/Jan/2023 19:32:51] [m"GET /users/3/buyer_account/2 HTTP/1.1" 200 94[0m
Not Found: /users/3/buyer_account/2/listings
[14/Jan/2023 19:32:56] [33m"GET /users/3/buyer_account/2/listings HTTP/1.1" 404 6183[0m
/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/users/urls.py changed, reloading.
[0mWatching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/usr/lib/python3/dist-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/lib/python3/dist-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/lib/python3/dist-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 416, in check
    for pattern in self.url_patterns:
  File "/usr/lib/python3/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python3/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/moundmusic/urls.py", line 30, in <module>
    path('users', include('users.urls')),
  File "/usr/lib/python3/dist-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/users/urls.py", line 15, in <module>
    path('<int:outer_model_obj_id>/buyer_account/<int:inner_model_obj_id>/listings/<int:third_model_obj_id>', views.single_user_single_buyer_account_single_listing),
AttributeError: module 'users.views' has no attribute 'single_user_single_buyer_account_single_listing'. Did you mean: 'single_user_single_buyer_account_any_listing'?
/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/users/urls.py changed, reloading.
[0mWatching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 14, 2023 - 19:33:16
Django version 3.2.15, using settings 'moundmusic.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /users/3/buyer_account/2/listings
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python3/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/lib/python3/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/lib/python3/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
TypeError: single_user_single_buyer_account_any_listing() got multiple values for argument 'outer_model_obj_id'
[14/Jan/2023 19:33:18] [35;1m"GET /users/3/buyer_account/2/listings HTTP/1.1" 500 91093[0m
/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/users/views.py changed, reloading.
[0mWatching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 14, 2023 - 19:33:42
Django version 3.2.15, using settings 'moundmusic.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[14/Jan/2023 19:33:43] [m"GET /users/3/buyer_account/2/listings HTTP/1.1" 200 349[0m
/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/users/views.py changed, reloading.
[0mWatching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 14, 2023 - 19:36:01
Django version 3.2.15, using settings 'moundmusic.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/users/views.py changed, reloading.
[0mWatching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 14, 2023 - 19:37:20
Django version 3.2.15, using settings 'moundmusic.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/users/views.py changed, reloading.
[0mWatching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 14, 2023 - 19:38:55
Django version 3.2.15, using settings 'moundmusic.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Not Found: /users/3/buyer_account/2/listings/5
[14/Jan/2023 19:39:18] [33m"GET /users/3/buyer_account/2/listings/5 HTTP/1.1" 404 6662[0m
/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/users/urls.py changed, reloading.
[0mWatching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 14, 2023 - 19:39:28
Django version 3.2.15, using settings 'moundmusic.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[14/Jan/2023 19:39:28] [m"GET /users/3/buyer_account/2/listings/5 HTTP/1.1" 200 115[0m
[14/Jan/2023 19:39:37] [m"DELETE /users/3/buyer_account/2/listings/5 HTTP/1.1" 200 62[0m
[14/Jan/2023 19:39:43] [m"GET /users/3/buyer_account/2/listings HTTP/1.1" 200 232[0m
/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/users/views.py changed, reloading.
[0mWatching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 14, 2023 - 19:46:11
Django version 3.2.15, using settings 'moundmusic.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/users/views.py changed, reloading.
[0mWatching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 14, 2023 - 19:46:59
Django version 3.2.15, using settings 'moundmusic.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/users/views.py changed, reloading.
[0mWatching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 14, 2023 - 19:47:56
Django version 3.2.15, using settings 'moundmusic.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /users/3/buyer_account/2/listings
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python3/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/lib/python3/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/lib/python3/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/users/views.py", line 263, in single_user_single_buyer_account_any_listing
    return dispatch_funcs_by_method((_single_user_single_buyer_account_any_listing_GET,
  File "/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/moundmusic/viewutils.py", line 63, in dispatch_funcs_by_method
    return dispatch_table[method]()
  File "/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/users/views.py", line 240, in _single_user_single_buyer_account_any_listing_POST
    json_content = validate_input(model_class, json_content, all_nullable=True)
NameError: name 'validate_input' is not defined
[14/Jan/2023 19:48:09] [35;1m"POST /users/3/buyer_account/2/listings HTTP/1.1" 500 106847[0m
/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/users/views.py changed, reloading.
[0mWatching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 14, 2023 - 19:48:22
Django version 3.2.15, using settings 'moundmusic.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /users/3/buyer_account/2/listings
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python3/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/lib/python3/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/lib/python3/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/users/views.py", line 263, in single_user_single_buyer_account_any_listing
    return dispatch_funcs_by_method((_single_user_single_buyer_account_any_listing_GET,
  File "/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/moundmusic/viewutils.py", line 63, in dispatch_funcs_by_method
    return dispatch_table[method]()
  File "/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/users/views.py", line 240, in _single_user_single_buyer_account_any_listing_POST
    json_content = validate_input(model_class, json_content, all_nullable=True)
NameError: name 'model_class' is not defined
[14/Jan/2023 19:48:23] [35;1m"POST /users/3/buyer_account/2/listings HTTP/1.1" 500 106829[0m
/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/users/views.py changed, reloading.
[0mWatching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 14, 2023 - 19:48:37
Django version 3.2.15, using settings 'moundmusic.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Bad Request: /users/3/buyer_account/2/listings
[14/Jan/2023 19:48:38] [31;1m"POST /users/3/buyer_account/2/listings HTTP/1.1" 400 75[0m
Bad Request: /users/3/buyer_account/2/listings
[14/Jan/2023 19:48:52] [31;1m"POST /users/3/buyer_account/2/listings HTTP/1.1" 400 33[0m
/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/albums/models.py changed, reloading.
[0mWatching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 14, 2023 - 19:49:29
Django version 3.2.15, using settings 'moundmusic.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/users/views.py changed, reloading.
[0mWatching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 14, 2023 - 19:49:30
Django version 3.2.15, using settings 'moundmusic.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[14/Jan/2023 19:49:36] [m"POST /users/3/buyer_account/2/listings HTTP/1.1" 200 116[0m
[14/Jan/2023 19:49:50] [m"GET /users/3/buyer_account/2/listings/58 HTTP/1.1" 200 116[0m
/home/kmfahey/Workspace/NuCampFolder/Python/3-DevOps/week3/portfolio_project/moundmusic/users/views.py changed, reloading.
[0mWatching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 14, 2023 - 19:50:03
Django version 3.2.15, using settings 'moundmusic.settings'
Starting 